CID-906 feat(auth-code-flow): Implement Authorisation Code Flow
connectid-tech/authorisation-code-flow-sample pull request #1
Opened 2021-12-08 02:15 UTC by diogo405

Description of changes:
* Implement Authorisation Code Flow
* PR template
* GH Workflow

Pre-checks:
* [x] Branch name is correct: `CID-XXX/type/short-description`
* [x] Pull request title follows the pattern `CID-XXX type(scope): Title of pull request`
* [x] `package.json` version has been updated
* [x] Tests have been added (if applicable)

2021-12-08 02:43 UTC, drmaciej commented on .github/workflows/build.yaml
> +        run: CLIENT_ID="$CLIENT_ID" REDIRECT_URI="$REDIRECT_URI" CLIENT_SECRET="$CLIENT_SECRET" npm start & npx wait-on -t 10000 http://localhost:8080
it's perfectly fine as is, but if you don't mind your commands a bit longer (it's already quite long), you could completely bypass `env` and just do
```
CLIENT_ID="${{ secrets.CLIENT_ID }}" REDIRECT_URI="${{ secrets.REDIRECT_URI }}" CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" npm start & npx wait-on -t 10000 http://localhost:8080
```
and the whole workflow will have fewer lines

2021-12-08 03:00 UTC, drmaciej reviewed
workflow LGTM, leaving the rest to @connectid-tech/frontend-reviewers

2021-12-13 03:39 UTC, guisilva-cid requested changes
blocking merges for now.

2022-03-06 21:03 UTC, guisilva-cid requested changes

2022-03-06 21:03 UTC, guisilva-cid commented on README.md
> +## Running on your machine
Won't the `config.json` also be used when deployed somewhere?

2022-03-06 21:03 UTC, guisilva-cid commented on README.md
> +When the login button is clicked the app will be redirected to an Identity Provider Selection page. Follow the steps below to proceed:
```suggestion
When the login button is clicked the app will be redirected to the Identity Provider Selection page. Follow the steps below to proceed:
```

2022-03-06 21:03 UTC, guisilva-cid commented on README.md
> +  "verified_claims": [ ],
```suggestion

```

2022-03-17 04:08 UTC, diogo405 commented on README.md
> +## Running on your machine
It always reads configuration from it. Some configs can be overridden:
```
const clientId = process.env.CLIENT_ID || config.clientId
const redirectUri = process.env.REDIRECT_URI || config.redirectUri
const clientSecret = process.env.CLIENT_SECRET || config.clientSecret
```

2022-03-17 04:32 UTC, StefanSchmidtOz approved these changes

2022-03-17 04:52 UTC, drmaciej commented on README.md
> +  "name": "Dr Jessica Anne Miller",
he Jessica, long time no see 🙃

2022-03-17 05:27 UTC, StefanSchmidtOz commented on README.md
> +  "name": "Dr Jessica Anne Miller",
Still on it. This PR is record breaking.
Why do we still have you here? Public repo!?

2022-03-17 05:55 UTC, diogo405 commented on README.md
> +  "name": "Dr Jessica Anne Miller",
It's a shame I can't re-request maciej review. I click and it doesn't work :/

2022-03-17 21:46 UTC, drmaciej approved these changes
lgtm :D

2022-03-21 22:35 UTC, guisilva-cid approved these changes

2022-03-21 22:50 UTC, merged